dateModified: 1625791675
email:
  fromEmail: ryan@mijingo.com
  fromName: Downlink
  template: null
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 4.3.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: Downlink
  schemaVersion: 3.6.4
  timeZone: UTC
